navbar:
  blog_title: Scarecrow41'Blog
  ground_glass:
    enable: true
index:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 100
  slogan:
    text: Just a test
post:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 70
  default_index_img: /images/uploads/1.jpg
archive:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
category:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
tag:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
about:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
  avatar: /img/avatar.png
  name: Scarecrow41'Blog
  intro: ...
links:
  banner_img: /images/uploads/1.jpg
  banner_img_height: 80
  items: []
